UENUM(Blueprintable)
enum Levels
{
	L_None   UMETA(DisplayName = "Level_None"),
	L_1   UMETA(DisplayName = "Level_1"),
	L_2   UMETA(DisplayName = "Level_2"),
	L_3   UMETA(DisplayName = "Level_3"),
	L_4   UMETA(DisplayName = "Level_4"),
	L_5   UMETA(DisplayName = "Level_5"),
	L_6   UMETA(DisplayName = "Level_6"),
	L_7   UMETA(DisplayName = "Level_7"),
	L_8   UMETA(DisplayName = "Level_8"),
	L_9   UMETA(DisplayName = "Level_9"),
	L_10   UMETA(DisplayName = "Level_10"),
	L_11   UMETA(DisplayName = "Level_11"),
	L_12   UMETA(DisplayName = "Level_12"),
	L_13   UMETA(DisplayName = "Level_13"),
	L_14   UMETA(DisplayName = "Level_14"),
	L_15   UMETA(DisplayName = "Level_15"),
	L_16   UMETA(DisplayName = "Level_16"),
	L_17   UMETA(DisplayName = "Level_17"),
	L_18   UMETA(DisplayName = "Level_18"),
	L_19   UMETA(DisplayName = "Level_19"),
	L_20   UMETA(DisplayName = "Level_20"),
	L_21   UMETA(DisplayName = "Level_21"),
	L_22   UMETA(DisplayName = "Level_22"),
	L_23   UMETA(DisplayName = "Level_23"),
	L_24   UMETA(DisplayName = "Level_24"),
	L_25   UMETA(DisplayName = "Level_25"),
	L_26   UMETA(DisplayName = "Level_26"),
	L_27   UMETA(DisplayName = "Level_27"),
	L_28   UMETA(DisplayName = "Level_28"),
	L_29   UMETA(DisplayName = "Level_29"),
	L_30   UMETA(DisplayName = "Level_30"),

};